name: possibility-for-electricity-autarky
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - numpy=1.13.3
  - pandas=0.23.2
  - gdal=2.4
  - matplotlib=3.1.0
  - seaborn=0.9
  - click=6.7
  - ipython
  - fiona=1.8.4
  - rasterio=1.0.18
  - rasterstats=0.13.0
  - geopandas=0.4.1
  - snakemake-minimal=5.4
  - xlrd=1.1.0
  - descartes=1.1
  - xarray=0.12.1
  - pip=19.1.1
  - pip:
      - pycountry
